package de.project.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-16T16:46:35.423+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://integration.project.de/", name = "ProjectIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectIntegration {

    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://integration.project.de/", className = "de.project.integration.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.CreateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ReturncodeResponse createProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getProjectsByPhone", targetNamespace = "http://integration.project.de/", className = "de.project.integration.GetProjectsByPhone")
    @ResponseWrapper(localName = "getProjectsByPhoneResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.GetProjectsByPhoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ProjectsResponse getProjectsByPhone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://integration.project.de/", className = "de.project.integration.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.UpdateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ProjectResponse updateProject(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );
}
