package de.project.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-15T22:47:13.256+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://integration.project.de/", name = "UserIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface UserIntegration {

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://integration.project.de/", className = "de.project.integration.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ReturncodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://integration.project.de/", className = "de.project.integration.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.RegisterUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ProjectUserResponse registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://integration.project.de/", className = "de.project.integration.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://integration.project.de/", className = "de.project.integration.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.project.integration.ProjectUserResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
